name: qgs
channels:
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.8
  - ipython
  - jupyter
  - matplotlib>=3.4
  - numba
  - numpy
  - scipy
  - sympy
  - sphinx
  - sphinx_rtd_theme>0.5.1
  - pytest
  - sparse
  - ffmpeg
  - pebble
  - pip
  - pip:
      - sphinxcontrib-bibtex
      - diffeqpy

